name: ZAP Website Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run ZAP Baseline Scan using Docker
    - name: ZAP Baseline Scan
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py \
          -t https://juice-shop.herokuapp.com/ \
          -r zap-report.html \
          --exit-code-on-fail 0
      continue-on-error: true  # workflow continues even if alerts are found

    # Upload ZAP report
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html
